// Spelling Bee / Word Hive Puzzle Database
export const SPELLING_BEE_HIVES = [
  {
    "id": 1,
    "centerLetter": "P",
    "outerLetters": [
      "A",
      "C",
      "E",
      "G",
      "H",
      "M"
    ],
    "allLetters": [
      "P",
      "A",
      "C",
      "E",
      "G",
      "H",
      "M"
    ],
    "pangrams": [
      "CHAMPAGNE"
    ],
    "validWords": [
      "AGAPE",
      "APACE",
      "CAMP",
      "CAPE",
      "CHAMP",
      "CHAMPAGNE",
      "CHEAP",
      "CHEEP",
      "EPHAH",
      "GAPE",
      "HEAP",
      "HEMP",
      "PACE",
      "PAGE",
      "PAMPA",
      "PAPA",
      "PEACE",
      "PEACH",
      "PEEP",
      "PHAGE"
    ],
    "wordCount": 20,
    "maxScore": 75,
    "theme": "Sparkling celebration"
  },
  {
    "id": 2,
    "centerLetter": "T",
    "outerLetters": [
      "A",
      "E",
      "G",
      "I",
      "L",
      "N"
    ],
    "allLetters": [
      "T",
      "A",
      "E",
      "G",
      "I",
      "L",
      "N"
    ],
    "pangrams": [
      "TRIANGLE"
    ],
    "validWords": [
      "AGATE",
      "AGENT",
      "ANENT",
      "ATILT",
      "EATEN",
      "ELATE",
      "ELITE",
      "GAIT",
      "GATE",
      "GENET",
      "GENT",
      "GIANT",
      "GILT",
      "GLINT",
      "GNAT",
      "INLET",
      "LATE",
      "LATIN",
      "LEANT",
      "LEGIT",
      "LENT",
      "LINT",
      "NATAL",
      "NEAT",
      "TAIL",
      "TAINT",
      "TALE",
      "TALL",
      "TEAL",
      "TEEN",
      "TELL",
      "TENET",
      "TENT",
      "TILE",
      "TILL",
      "TILT",
      "TINGE",
      "TINT",
      "TITAN",
      "TITLE",
      "TRIANGLE"
    ],
    "wordCount": 41,
    "maxScore": 135,
    "theme": "Geometry & acute angles"
  },
  {
    "id": 3,
    "centerLetter": "O",
    "outerLetters": [
      "A",
      "C",
      "E",
      "G",
      "R",
      "U"
    ],
    "allLetters": [
      "O",
      "A",
      "C",
      "E",
      "G",
      "R",
      "U"
    ],
    "pangrams": [
      "COURAGE"
    ],
    "validWords": [
      "AGORA",
      "CACAO",
      "CARGO",
      "COCA",
      "COCO",
      "COCOA",
      "CORE",
      "CORER",
      "COURAGE",
      "ERROR",
      "GORE",
      "GORGE",
      "GOUGE",
      "GROG",
      "OCCUR",
      "OGRE",
      "ROAR",
      "ROGER",
      "ROGUE",
      "ROUGE"
    ],
    "wordCount": 20,
    "maxScore": 81,
    "theme": "Bravery & valor"
  },
  {
    "id": 4,
    "centerLetter": "U",
    "outerLetters": [
      "A",
      "B",
      "E",
      "F",
      "I",
      "L"
    ],
    "allLetters": [
      "U",
      "A",
      "B",
      "E",
      "F",
      "I",
      "L"
    ],
    "pangrams": [
      "BEAUTIFUL"
    ],
    "validWords": [
      "BEAU",
      "BEAUTIFUL",
      "BLUE",
      "BLUFF",
      "BUBBA",
      "BUFF",
      "BUFFA",
      "BULB",
      "BULL",
      "FLUFF",
      "FUEL",
      "FULL",
      "LULAB"
    ],
    "wordCount": 13,
    "maxScore": 50,
    "theme": "Grace & aesthetic"
  },
  {
    "id": 5,
    "centerLetter": "P",
    "outerLetters": [
      "A",
      "D",
      "G",
      "L",
      "O",
      "R"
    ],
    "allLetters": [
      "P",
      "A",
      "D",
      "G",
      "L",
      "O",
      "R"
    ],
    "pangrams": [
      "PLAYGROUND"
    ],
    "validWords": [
      "DROOP",
      "DROP",
      "LOOP",
      "OPAL",
      "PAPA",
      "PAPAL",
      "PLAYGROUND",
      "PLOD",
      "POLAR",
      "POLL",
      "POLO",
      "POOL",
      "POOP",
      "POOR",
      "PROD",
      "PROP"
    ],
    "wordCount": 16,
    "maxScore": 50,
    "theme": "Parks & recreation"
  },
  {
    "id": 6,
    "centerLetter": "D",
    "outerLetters": [
      "A",
      "I",
      "M",
      "N",
      "O",
      "S"
    ],
    "allLetters": [
      "D",
      "A",
      "I",
      "M",
      "N",
      "O",
      "S"
    ],
    "pangrams": [
      "DIAMONDS"
    ],
    "validWords": [
      "ADIOS",
      "ADMAN",
      "AIDS",
      "DADOS",
      "DAIS",
      "DAMNS",
      "DAMS",
      "DIAMOND",
      "DIAMONDS",
      "DIDOS",
      "DODOS",
      "DODS",
      "DONNA",
      "DOOM",
      "DOOMS",
      "IDIOM",
      "MADAM",
      "MAID",
      "MAIDS",
      "MIDIS",
      "MIND",
      "MINDS",
      "MONAD",
      "MONDO",
      "MOOD",
      "MOODS",
      "NAIAD",
      "NODS",
      "NOMAD",
      "ODDS",
      "SAID",
      "SAND",
      "SANDS",
      "SNOOD",
      "SODA",
      "SODAS"
    ],
    "wordCount": 36,
    "maxScore": 140,
    "theme": "Precious crystals"
  },
  {
    "id": 7,
    "centerLetter": "A",
    "outerLetters": [
      "C",
      "E",
      "G",
      "K",
      "P",
      "R"
    ],
    "allLetters": [
      "A",
      "C",
      "E",
      "G",
      "K",
      "P",
      "R"
    ],
    "pangrams": [
      "PACKAGE"
    ],
    "validWords": [
      "ACRE",
      "AGAPE",
      "AGREE",
      "APACE",
      "AREA",
      "CAGE",
      "CAGER",
      "CAKE",
      "CAPE",
      "CAPER",
      "CARE",
      "CARER",
      "CARP",
      "CRACK",
      "CRAG",
      "CRAP",
      "CREAK",
      "EAGER",
      "GAGE",
      "GAPE",
      "GAPER",
      "GEAR",
      "GRACE",
      "GRAPE",
      "KAPPA",
      "PACE",
      "PACER",
      "PACK",
      "PACKAGE",
      "PAGE",
      "PAGER",
      "PAPA",
      "PAPER",
      "PARER",
      "PARK",
      "PARKA",
      "PEACE",
      "PEAK",
      "PEAR",
      "RACE",
      "RACER",
      "RACK",
      "RAGE",
      "RAKE",
      "RAKER",
      "RAPER",
      "RARE",
      "RARER",
      "REAP",
      "REAR",
      "RECAP"
    ],
    "wordCount": 51,
    "maxScore": 160,
    "theme": "Delivery & parcels"
  },
  {
    "id": 8,
    "centerLetter": "J",
    "outerLetters": [
      "E",
      "N",
      "O",
      "R",
      "U",
      "Y"
    ],
    "allLetters": [
      "J",
      "E",
      "N",
      "O",
      "R",
      "U",
      "Y"
    ],
    "pangrams": [
      "JOURNEY"
    ],
    "validWords": [
      "ENJOY",
      "JEER",
      "JENNY",
      "JERRY",
      "JOURNEY",
      "JUROR",
      "JURY"
    ],
    "wordCount": 7,
    "maxScore": 50,
    "theme": "Travel & voyage"
  },
  {
    "id": 9,
    "centerLetter": "Y",
    "outerLetters": [
      "A",
      "F",
      "N",
      "S",
      "T",
      "Z"
    ],
    "allLetters": [
      "Y",
      "A",
      "F",
      "N",
      "S",
      "T",
      "Z"
    ],
    "pangrams": [
      "FANTASY"
    ],
    "validWords": [
      "ANTSY",
      "ASSAY",
      "FANNY",
      "FANTASY",
      "FATTY",
      "NANNY",
      "NASTY",
      "NATTY",
      "SASSY",
      "SAYS",
      "STAY",
      "STAYS",
      "TAFFY",
      "TANSY",
      "TASTY",
      "TATTY"
    ],
    "wordCount": 16,
    "maxScore": 81,
    "theme": "Dreams & magic"
  },
  {
    "id": 10,
    "centerLetter": "B",
    "outerLetters": [
      "A",
      "I",
      "N",
      "O",
      "R",
      "W"
    ],
    "allLetters": [
      "B",
      "A",
      "I",
      "N",
      "O",
      "R",
      "W"
    ],
    "pangrams": [
      "RAINBOW"
    ],
    "validWords": [
      "ARBOR",
      "BAIRN",
      "BARN",
      "BARON",
      "BOAR",
      "BOON",
      "BORN",
      "BORON",
      "BRAIN",
      "BRAN",
      "BRAWN",
      "BRIAR",
      "BROWN",
      "BWANA",
      "NABOB",
      "RABBI",
      "RAINBOW",
      "ROBIN"
    ],
    "wordCount": 18,
    "maxScore": 79,
    "theme": "Sky spectrum"
  },
  {
    "id": 11,
    "centerLetter": "C",
    "outerLetters": [
      "A",
      "H",
      "M",
      "N",
      "O",
      "R"
    ],
    "allLetters": [
      "C",
      "A",
      "H",
      "M",
      "N",
      "O",
      "R"
    ],
    "pangrams": [
      "MONARCH"
    ],
    "validWords": [
      "ACHOO",
      "ACORN",
      "CACAO",
      "CANNA",
      "CANON",
      "CAROM",
      "CARON",
      "CHARM",
      "COACH",
      "COCA",
      "COCO",
      "COCOA",
      "COMMA",
      "CONCH",
      "COOCH",
      "CORN",
      "CRAM",
      "CRAN",
      "CROON",
      "HOOCH",
      "MACHO",
      "MACRO",
      "MARCH",
      "MOCHA",
      "MONARCH",
      "MOOCH",
      "NACHO",
      "NARCO",
      "RANCH",
      "ROACH"
    ],
    "wordCount": 30,
    "maxScore": 139,
    "theme": "Royalty & butterflies"
  },
  {
    "id": 12,
    "centerLetter": "E",
    "outerLetters": [
      "A",
      "C",
      "I",
      "R",
      "T",
      "V"
    ],
    "allLetters": [
      "E",
      "A",
      "C",
      "I",
      "R",
      "T",
      "V"
    ],
    "pangrams": [
      "CREATIVE"
    ],
    "validWords": [
      "ACRE",
      "AERIE",
      "AIRER",
      "AREA",
      "AVERT",
      "CARE",
      "CARER",
      "CARET",
      "CARTE",
      "CARVE",
      "CATER",
      "CAVE",
      "CIVET",
      "CRATE",
      "CRAVE",
      "CREATIVE",
      "CRIER",
      "EATER",
      "EERIE",
      "ERECT",
      "EVER",
      "EVICT",
      "ICIER",
      "IRATE",
      "RACE",
      "RACER",
      "RARE",
      "RARER",
      "RATE",
      "RATER",
      "RAVE",
      "RAVER",
      "REACT",
      "REAR",
      "RECTA",
      "REEVE",
      "REVET",
      "RICE",
      "RICER",
      "RITE",
      "RIVER",
      "RIVET",
      "TACET",
      "TARE",
      "TATER",
      "TEAR",
      "TERCE",
      "TERRA",
      "TETRA",
      "TIER",
      "TIRE",
      "TITER",
      "TITRE",
      "TRACE",
      "TREAT",
      "TREE",
      "TRICE",
      "TRIER",
      "TRITE",
      "VEER",
      "VERVE",
      "VICE",
      "VITAE",
      "VIVRE"
    ],
    "wordCount": 64,
    "maxScore": 254,
    "theme": "Imagination & art"
  },
  {
    "id": 13,
    "centerLetter": "H",
    "outerLetters": [
      "A",
      "M",
      "N",
      "O",
      "R",
      "Y"
    ],
    "allLetters": [
      "H",
      "A",
      "M",
      "N",
      "O",
      "R",
      "Y"
    ],
    "pangrams": [
      "HARMONY"
    ],
    "validWords": [
      "AHHHH",
      "HAMMY",
      "HARM",
      "HARMONY",
      "HARRY",
      "HOARY",
      "HONOR",
      "HORN",
      "HORNY",
      "HYMN",
      "MYNAH",
      "MYRRH",
      "OHHHH",
      "YAHOO"
    ],
    "wordCount": 14,
    "maxScore": 67,
    "theme": "Musical accord"
  },
  {
    "id": 14,
    "centerLetter": "P",
    "outerLetters": [
      "D",
      "H",
      "I",
      "L",
      "N",
      "O"
    ],
    "allLetters": [
      "P",
      "D",
      "H",
      "I",
      "L",
      "N",
      "O"
    ],
    "pangrams": [
      "DOLPHIN"
    ],
    "validWords": [
      "DOLPHIN",
      "HIPPO",
      "HOOP",
      "LIPID",
      "LOOP",
      "PILL",
      "PLOD",
      "POLIO",
      "POLL",
      "POLO",
      "POND",
      "POOL",
      "POOP"
    ],
    "wordCount": 13,
    "maxScore": 50,
    "theme": "Ocean mammal"
  },
  {
    "id": 15,
    "centerLetter": "V",
    "outerLetters": [
      "A",
      "E",
      "F",
      "I",
      "L",
      "S"
    ],
    "allLetters": [
      "V",
      "A",
      "E",
      "F",
      "I",
      "L",
      "S"
    ],
    "pangrams": [
      "FESTIVAL"
    ],
    "validWords": [
      "ALIVE",
      "AVAIL",
      "EAVES",
      "ELVES",
      "EVIL",
      "EVILS",
      "FESTIVAL",
      "FIVE",
      "FIVES",
      "IVIES",
      "LAVA",
      "LAVAS",
      "LAVES",
      "LEAVE",
      "LEVEE",
      "LEVEL",
      "LEVIS",
      "LIVE",
      "LIVES",
      "SALVE",
      "SAVE",
      "SAVES",
      "SIEVE",
      "SLAVE",
      "VAILS",
      "VALE",
      "VALES",
      "VALVE",
      "VASE",
      "VASES",
      "VEAL",
      "VEALS",
      "VEIL",
      "VEILS",
      "VIAL",
      "VIALS",
      "VILLA",
      "VILLE",
      "VILLI",
      "VISA",
      "VISAS",
      "VISE",
      "VISES",
      "VIVAS"
    ],
    "wordCount": 44,
    "maxScore": 182,
    "theme": "Carnival & jubilee"
  },
  {
    "id": 16,
    "centerLetter": "Z",
    "outerLetters": [
      "H",
      "I",
      "N",
      "O",
      "R",
      "E"
    ],
    "allLetters": [
      "Z",
      "H",
      "I",
      "N",
      "O",
      "R",
      "E"
    ],
    "pangrams": [
      "HORIZON"
    ],
    "validWords": [
      "HORIZON",
      "OOZE",
      "OZONE",
      "ZERO",
      "ZONE"
    ],
    "wordCount": 5,
    "maxScore": 50,
    "theme": "Where earth meets sky"
  },
  {
    "id": 17,
    "centerLetter": "V",
    "outerLetters": [
      "A",
      "E",
      "I",
      "M",
      "P",
      "R"
    ],
    "allLetters": [
      "V",
      "A",
      "E",
      "I",
      "M",
      "P",
      "R"
    ],
    "pangrams": [
      "VAMPIRE"
    ],
    "validWords": [
      "EVER",
      "PAVE",
      "PAVER",
      "PEEVE",
      "RAVE",
      "RAVER",
      "REEVE",
      "RIVER",
      "VAMP",
      "VAMPIRE",
      "VARIA",
      "VEER",
      "VERVE",
      "VIPER",
      "VIVRE"
    ],
    "wordCount": 15,
    "maxScore": 64,
    "theme": "Nocturnal legends"
  },
  {
    "id": 18,
    "centerLetter": "P",
    "outerLetters": [
      "A",
      "D",
      "I",
      "M",
      "R",
      "Y"
    ],
    "allLetters": [
      "P",
      "A",
      "D",
      "I",
      "M",
      "R",
      "Y"
    ],
    "pangrams": [
      "PYRAMID"
    ],
    "validWords": [
      "DAMP",
      "DIPPY",
      "DRIP",
      "PADDY",
      "PAID",
      "PAIR",
      "PAMPA",
      "PAPA",
      "PAPPY",
      "PARRY",
      "PRAY",
      "PRIM",
      "PRIMA",
      "PRIMP",
      "PYRAMID",
      "RAMP",
      "RAPID"
    ],
    "wordCount": 17,
    "maxScore": 62,
    "theme": "Ancient monument"
  },
  {
    "id": 19,
    "centerLetter": "B",
    "outerLetters": [
      "L",
      "M",
      "O",
      "S",
      "E",
      "A"
    ],
    "allLetters": [
      "B",
      "L",
      "M",
      "O",
      "S",
      "E",
      "A"
    ],
    "pangrams": [
      "BLOSSOM"
    ],
    "validWords": [
      "ABASE",
      "ABEAM",
      "ABLE",
      "AMBLE",
      "AMEBA",
      "BABEL",
      "BABES",
      "BALE",
      "BALES",
      "BALL",
      "BALLS",
      "BALMS",
      "BALSA",
      "BASAL",
      "BASE",
      "BASES",
      "BASS",
      "BASSO",
      "BEAM",
      "BEAMS",
      "BEES",
      "BELL",
      "BELLE",
      "BELLS",
      "BLABS",
      "BLAME",
      "BLEBS",
      "BLESS",
      "BLOBS",
      "BLOOM",
      "BLOSSOM",
      "BOLAS",
      "BOLLS",
      "BOLOS",
      "BOMBE",
      "BOMBS",
      "BOOBS",
      "BOOM",
      "BOOMS",
      "BOSOM",
      "BOSS",
      "BOSSA",
      "LABEL",
      "LABS",
      "LAMB",
      "LAMBS",
      "LOBE",
      "LOBES",
      "MAMBO",
      "MEBBE",
      "MELBA",
      "OBESE",
      "OBOES",
      "SABLE",
      "SAMBA",
      "SLAB",
      "SLABS",
      "SLOB",
      "SLOBS"
    ],
    "wordCount": 59,
    "maxScore": 244,
    "theme": "Spring bloom"
  },
  {
    "id": 20,
    "centerLetter": "G",
    "outerLetters": [
      "E",
      "I",
      "N",
      "P",
      "U",
      "A"
    ],
    "allLetters": [
      "G",
      "E",
      "I",
      "N",
      "P",
      "U",
      "A"
    ],
    "pangrams": [
      "PENGUIN"
    ],
    "validWords": [
      "AGAIN",
      "AGAPE",
      "AGING",
      "APING",
      "GAGE",
      "GAIN",
      "GANG",
      "GAPE",
      "GAUGE",
      "GENE",
      "GENIE",
      "GENII",
      "GIGUE",
      "PAGAN",
      "PAGE",
      "PANG",
      "PANGA",
      "PENGUIN",
      "PIING",
      "PING",
      "UNPEG"
    ],
    "wordCount": 21,
    "maxScore": 82,
    "theme": "Antarctic bird"
  },
  {
    "id": 21,
    "centerLetter": "P",
    "outerLetters": [
      "A",
      "H",
      "M",
      "N",
      "O",
      "T"
    ],
    "allLetters": [
      "P",
      "A",
      "H",
      "M",
      "N",
      "O",
      "T"
    ],
    "pangrams": [
      "PHANTOM"
    ],
    "validWords": [
      "HOOP",
      "OOMPH",
      "PAMPA",
      "PANT",
      "PAPA",
      "PATH",
      "PHANTOM",
      "PHOTO",
      "POOP"
    ],
    "wordCount": 9,
    "maxScore": 50,
    "theme": "Ghostly apparition"
  },
  {
    "id": 22,
    "centerLetter": "B",
    "outerLetters": [
      "A",
      "L",
      "N",
      "O",
      "E",
      "I"
    ],
    "allLetters": [
      "B",
      "A",
      "L",
      "N",
      "O",
      "E",
      "I"
    ],
    "pangrams": [
      "BALLOON"
    ],
    "validWords": [
      "ABLE",
      "ALIBI",
      "BABEL",
      "BAIL",
      "BALE",
      "BALL",
      "BALLOON",
      "BANAL",
      "BANE",
      "BEAN",
      "BEANO",
      "BEEN",
      "BELIE",
      "BELL",
      "BELLE",
      "BELLI",
      "BIBLE",
      "BILE",
      "BILL",
      "BLINI",
      "BOIL",
      "BONE",
      "BONNE",
      "BOON",
      "LABEL",
      "LABIA",
      "LIBEL",
      "LOBE",
      "NABLA",
      "NABOB",
      "NOBLE"
    ],
    "wordCount": 31,
    "maxScore": 108,
    "theme": "Helium float"
  },
  {
    "id": 23,
    "centerLetter": "F",
    "outerLetters": [
      "A",
      "E",
      "H",
      "R",
      "T",
      "I"
    ],
    "allLetters": [
      "F",
      "A",
      "E",
      "H",
      "R",
      "T",
      "I"
    ],
    "pangrams": [
      "FEATHER"
    ],
    "validWords": [
      "AFIRE",
      "AFTER",
      "FAIR",
      "FAIRE",
      "FAITH",
      "FARE",
      "FATE",
      "FEAR",
      "FEAT",
      "FEATHER",
      "FEET",
      "FIAT",
      "FIEF",
      "FIFTH",
      "FIRE",
      "FIRER",
      "FIRTH",
      "FREE",
      "FREER",
      "FRET",
      "FRIAR",
      "FRIER",
      "HAFTA",
      "RAFT",
      "REEF",
      "REFER",
      "REFIT",
      "RIFE",
      "RIFER",
      "RIFF",
      "RIFT",
      "THEFT",
      "THIEF"
    ],
    "wordCount": 33,
    "maxScore": 110,
    "theme": "Light plumage"
  },
  {
    "id": 24,
    "centerLetter": "L",
    "outerLetters": [
      "A",
      "E",
      "N",
      "R",
      "T",
      "I"
    ],
    "allLetters": [
      "L",
      "A",
      "E",
      "N",
      "R",
      "T",
      "I"
    ],
    "pangrams": [
      "LANTERN"
    ],
    "validWords": [
      "ALERT",
      "ALIEN",
      "ALTAR",
      "ALTER",
      "ANILE",
      "AREAL",
      "ATILT",
      "EARL",
      "ELATE",
      "ELITE",
      "INLET",
      "LAIR",
      "LANAI",
      "LANE",
      "LANTERN",
      "LATE",
      "LATER",
      "LATIN",
      "LEAN",
      "LEANT",
      "LEAR",
      "LEARN",
      "LENT",
      "LIAR",
      "LIEN",
      "LINE",
      "LINEN",
      "LINER",
      "LINT",
      "LITER",
      "LITRE",
      "NAIL",
      "NATAL",
      "RAIL",
      "REAL",
      "REEL",
      "RELET",
      "RENAL",
      "RILLE",
      "TAIL",
      "TALE",
      "TALL",
      "TEAL",
      "TELL",
      "TILE",
      "TILER",
      "TILL",
      "TILT",
      "TITLE",
      "TRAIL",
      "TRIAL",
      "TRILL"
    ],
    "wordCount": 52,
    "maxScore": 177,
    "theme": "Beacon of light"
  },
  {
    "id": 25,
    "centerLetter": "C",
    "outerLetters": [
      "A",
      "M",
      "O",
      "P",
      "S",
      "E"
    ],
    "allLetters": [
      "C",
      "A",
      "M",
      "O",
      "P",
      "S",
      "E"
    ],
    "pangrams": [
      "COMPASS"
    ],
    "validWords": [
      "ACES",
      "ACMES",
      "APACE",
      "CACAO",
      "CAME",
      "CAMEO",
      "CAMP",
      "CAMPO",
      "CAMPS",
      "CAPE",
      "CAPES",
      "CAPOS",
      "CAPS",
      "CASAS",
      "CASE",
      "CASES",
      "CEASE",
      "COCA",
      "COCAS",
      "COCO",
      "COCOA",
      "COCOS",
      "COMAS",
      "COME",
      "COMES",
      "COMMA",
      "COMPASS",
      "COMPS",
      "COOP",
      "COOPS",
      "COPE",
      "COPES",
      "COPS",
      "COPSE",
      "EMCEE",
      "MACE",
      "MACES",
      "MECCA",
      "PACE",
      "PACES",
      "PEACE",
      "SCAM",
      "SCAMP",
      "SCAMS",
      "SCOOP",
      "SCOPE",
      "SCOPS",
      "SECCO",
      "SPACE",
      "SPEC",
      "SPECS"
    ],
    "wordCount": 51,
    "maxScore": 200,
    "theme": "Navigation tool"
  },
  {
    "id": 26,
    "centerLetter": "V",
    "outerLetters": [
      "A",
      "C",
      "L",
      "N",
      "O",
      "E"
    ],
    "allLetters": [
      "V",
      "A",
      "C",
      "L",
      "N",
      "O",
      "E"
    ],
    "pangrams": [
      "VOLCANO"
    ],
    "validWords": [
      "CALVE",
      "CAVE",
      "CLAVE",
      "CLOVE",
      "COVE",
      "COVEN",
      "EVEN",
      "LAVA",
      "LEAVE",
      "LEVEE",
      "LEVEL",
      "LOVE",
      "NAVAL",
      "NAVEL",
      "NOVA",
      "NOVAE",
      "NOVEL",
      "OVAL",
      "OVEN",
      "VALE",
      "VALVE",
      "VANE",
      "VEAL",
      "VENAL",
      "VOCAL",
      "VOLCANO"
    ],
    "wordCount": 26,
    "maxScore": 95,
    "theme": "Molten earth"
  },
  {
    "id": 27,
    "centerLetter": "C",
    "outerLetters": [
      "A",
      "L",
      "R",
      "S",
      "T",
      "Y"
    ],
    "allLetters": [
      "C",
      "A",
      "L",
      "R",
      "S",
      "T",
      "Y"
    ],
    "pangrams": [
      "CRYSTAL"
    ],
    "validWords": [
      "ACTS",
      "ARCS",
      "CALL",
      "CALLA",
      "CALLS",
      "CARAT",
      "CARRY",
      "CARS",
      "CART",
      "CARTS",
      "CASAS",
      "CAST",
      "CASTS",
      "CATS",
      "CATTY",
      "CLASS",
      "CLAY",
      "CLAYS",
      "CRASS",
      "CRYSTAL",
      "CYSTS",
      "LACY",
      "LYCRA",
      "SCALY",
      "SCAR",
      "SCARS",
      "SCARY",
      "SCAT",
      "SCATS",
      "TACT",
      "TACTS",
      "TALCS",
      "TRACT"
    ],
    "wordCount": 33,
    "maxScore": 126,
    "theme": "Glistening mineral"
  },
  {
    "id": 28,
    "centerLetter": "W",
    "outerLetters": [
      "E",
      "H",
      "I",
      "P",
      "R",
      "S"
    ],
    "allLetters": [
      "W",
      "E",
      "H",
      "I",
      "P",
      "R",
      "S"
    ],
    "pangrams": [
      "WHISPER"
    ],
    "validWords": [
      "HEWER",
      "PEWEE",
      "RESEW",
      "SEWER",
      "SEWS",
      "SHEWS",
      "SHREW",
      "SPEW",
      "SPEWS",
      "SWEEP",
      "SWIPE",
      "SWISH",
      "SWISS",
      "WEEP",
      "WEEPS",
      "WEIRS",
      "WERE",
      "WHEEE",
      "WHERE",
      "WHEWS",
      "WHIP",
      "WHIPS",
      "WHIR",
      "WHIRR",
      "WHIRS",
      "WHISH",
      "WHISPER",
      "WIPE",
      "WIPER",
      "WIPES",
      "WIRE",
      "WIRER",
      "WIRES",
      "WISE",
      "WISER",
      "WISES",
      "WISH",
      "WISP",
      "WISPS",
      "WRIER"
    ],
    "wordCount": 40,
    "maxScore": 165,
    "theme": "Hushed words"
  },
  {
    "id": 29,
    "centerLetter": "J",
    "outerLetters": [
      "A",
      "L",
      "N",
      "O",
      "R",
      "U"
    ],
    "allLetters": [
      "J",
      "A",
      "L",
      "N",
      "O",
      "R",
      "U"
    ],
    "pangrams": [
      "JOURNAL"
    ],
    "validWords": [
      "JOURNAL",
      "JUROR"
    ],
    "wordCount": 2,
    "maxScore": 50,
    "theme": "Personal diary"
  },
  {
    "id": 30,
    "centerLetter": "K",
    "outerLetters": [
      "A",
      "B",
      "E",
      "L",
      "N",
      "T"
    ],
    "allLetters": [
      "K",
      "A",
      "B",
      "E",
      "L",
      "N",
      "T"
    ],
    "pangrams": [
      "BLANKET"
    ],
    "validWords": [
      "ANKLE",
      "BAKE",
      "BANK",
      "BEAK",
      "BLANK",
      "BLANKET",
      "BLEAK",
      "KEBAB",
      "KEEL",
      "KEEN",
      "KNEE",
      "KNEEL",
      "KNELL",
      "KNELT",
      "LAKE",
      "LEAK",
      "TAKE",
      "TAKEN",
      "TALK",
      "TANK"
    ],
    "wordCount": 20,
    "maxScore": 65,
    "theme": "Cozy warmth"
  },
  {
    "id": 31,
    "centerLetter": "X",
    "outerLetters": [
      "E",
      "L",
      "O",
      "P",
      "R",
      "A"
    ],
    "allLetters": [
      "X",
      "E",
      "L",
      "O",
      "P",
      "R",
      "A"
    ],
    "pangrams": [
      "EXPLORE"
    ],
    "validWords": [
      "APEX",
      "EXPEL",
      "EXPLORE",
      "EXPO",
      "LAXER",
      "RELAX",
      "XEROX"
    ],
    "wordCount": 7,
    "maxScore": 50,
    "theme": "Adventurous quest"
  },
  {
    "id": 32,
    "centerLetter": "G",
    "outerLetters": [
      "A",
      "D",
      "N",
      "O",
      "R",
      "E"
    ],
    "allLetters": [
      "G",
      "A",
      "D",
      "N",
      "O",
      "R",
      "E"
    ],
    "pangrams": [
      "DRAGON"
    ],
    "validWords": [
      "ADAGE",
      "AGED",
      "AGONE",
      "AGORA",
      "AGREE",
      "ANGER",
      "ARGON",
      "DODGE",
      "DOGGO",
      "DRAG",
      "DRAGON",
      "EAGER",
      "EDGE",
      "EDGED",
      "EDGER",
      "EGGED",
      "EGGER",
      "GAGE",
      "GANG",
      "GARDE",
      "GEAR",
      "GENE",
      "GENRE",
      "GEODE",
      "GOAD",
      "GONAD",
      "GONE",
      "GONER",
      "GONG",
      "GONNA",
      "GOOD",
      "GOON",
      "GORE",
      "GORED",
      "GORGE",
      "GRAD",
      "GRADE",
      "GRAN",
      "GRAND",
      "GREED",
      "GREEN",
      "GROAN",
      "GROG",
      "NEGRO",
      "OGRE",
      "ORGAN",
      "RAGE",
      "RAGED",
      "RANG",
      "RANGE",
      "ROGER"
    ],
    "wordCount": 51,
    "maxScore": 187,
    "theme": "Mythic creature"
  },
  {
    "id": 33,
    "centerLetter": "G",
    "outerLetters": [
      "A",
      "L",
      "X",
      "Y",
      "E",
      "I"
    ],
    "allLetters": [
      "G",
      "A",
      "L",
      "X",
      "Y",
      "E",
      "I"
    ],
    "pangrams": [
      "GALAXY"
    ],
    "validWords": [
      "AGILE",
      "AGLEY",
      "ALGAE",
      "ALGAL",
      "EAGLE",
      "ELEGY",
      "GAGE",
      "GAILY",
      "GALA",
      "GALAXY",
      "GALE",
      "GALL",
      "GAYLY",
      "GILL",
      "GLEE",
      "LEGAL",
      "LEGGY",
      "LIEGE"
    ],
    "wordCount": 18,
    "maxScore": 74,
    "theme": "Cosmic spiral"
  },
  {
    "id": 34,
    "centerLetter": "U",
    "outerLetters": [
      "C",
      "I",
      "N",
      "O",
      "R",
      "E"
    ],
    "allLetters": [
      "U",
      "C",
      "I",
      "N",
      "O",
      "R",
      "E"
    ],
    "pangrams": [
      "UNICORN"
    ],
    "validWords": [
      "CORNU",
      "CURE",
      "CURER",
      "CURIE",
      "CURIO",
      "ENNUI",
      "INCUR",
      "INURE",
      "NOUN",
      "OCCUR",
      "OUNCE",
      "RECUR",
      "RERUN",
      "RUIN",
      "RUNIC",
      "UNICORN",
      "UNION",
      "URINE"
    ],
    "wordCount": 18,
    "maxScore": 87,
    "theme": "Horned stallion"
  },
  {
    "id": 35,
    "centerLetter": "J",
    "outerLetters": [
      "A",
      "E",
      "M",
      "S",
      "T",
      "Y"
    ],
    "allLetters": [
      "J",
      "A",
      "E",
      "M",
      "S",
      "T",
      "Y"
    ],
    "pangrams": [
      "MAJESTY"
    ],
    "validWords": [
      "JAMMY",
      "JAMS",
      "JAYS",
      "JEST",
      "JESTS",
      "JETS",
      "JETTY",
      "MAJESTY"
    ],
    "wordCount": 8,
    "maxScore": 50,
    "theme": "Grand grandeur"
  },
  {
    "id": 36,
    "centerLetter": "V",
    "outerLetters": [
      "A",
      "E",
      "G",
      "I",
      "N",
      "T"
    ],
    "allLetters": [
      "V",
      "A",
      "E",
      "G",
      "I",
      "N",
      "T"
    ],
    "pangrams": [
      "VINTAGE"
    ],
    "validWords": [
      "AGAVE",
      "AVANT",
      "AVIAN",
      "EVEN",
      "EVENT",
      "GAVE",
      "GIVE",
      "GIVEN",
      "NAIVE",
      "VANE",
      "VEGAN",
      "VEIN",
      "VENT",
      "VINE",
      "VINTAGE",
      "VITAE"
    ],
    "wordCount": 16,
    "maxScore": 61,
    "theme": "Classic antique"
  },
  {
    "id": 37,
    "centerLetter": "C",
    "outerLetters": [
      "A",
      "E",
      "H",
      "R",
      "I",
      "O"
    ],
    "allLetters": [
      "C",
      "A",
      "E",
      "H",
      "R",
      "I",
      "O"
    ],
    "pangrams": [
      "ARCHER"
    ],
    "validWords": [
      "ACHE",
      "ACHOO",
      "ACRE",
      "ARCHER",
      "CACAO",
      "CACHE",
      "CARE",
      "CARER",
      "CHAIR",
      "CHEER",
      "CHOIR",
      "CHORE",
      "CIRCA",
      "CIRRI",
      "COACH",
      "COCA",
      "COCCI",
      "COCO",
      "COCOA",
      "COOCH",
      "CORE",
      "CORER",
      "CRIER",
      "EACH",
      "ECHO",
      "HOOCH",
      "ICHOR",
      "ICIER",
      "OCHER",
      "OCHRE",
      "RACE",
      "RACER",
      "REACH",
      "RICE",
      "RICER",
      "RICH",
      "ROACH"
    ],
    "wordCount": 37,
    "maxScore": 149,
    "theme": "Bow & arrow"
  },
  {
    "id": 38,
    "centerLetter": "C",
    "outerLetters": [
      "A",
      "I",
      "N",
      "P",
      "T",
      "E"
    ],
    "allLetters": [
      "C",
      "A",
      "I",
      "N",
      "P",
      "T",
      "E"
    ],
    "pangrams": [
      "CAPTAIN"
    ],
    "validWords": [
      "ACTIN",
      "ANTIC",
      "APACE",
      "ATTIC",
      "CACTI",
      "CANE",
      "CANNA",
      "CAPE",
      "CAPTAIN",
      "CENT",
      "ENACT",
      "EPACT",
      "EPIC",
      "NICE",
      "NIECE",
      "PACE",
      "PACT",
      "PANIC",
      "PEACE",
      "PECAN",
      "PENCE",
      "PIECE",
      "TACET",
      "TACIT",
      "TACT"
    ],
    "wordCount": 25,
    "maxScore": 102,
    "theme": "Ship commander"
  },
  {
    "id": 39,
    "centerLetter": "F",
    "outerLetters": [
      "E",
      "N",
      "O",
      "R",
      "T",
      "U"
    ],
    "allLetters": [
      "F",
      "E",
      "N",
      "O",
      "R",
      "T",
      "U"
    ],
    "pangrams": [
      "FORTUNE"
    ],
    "validWords": [
      "FEET",
      "FERN",
      "FETOR",
      "FONT",
      "FOOT",
      "FORT",
      "FORTE",
      "FORTUNE",
      "FOUNT",
      "FOUR",
      "FREE",
      "FREER",
      "FRET",
      "FRONT",
      "FUROR",
      "FUTON",
      "OFFEN",
      "OFFER",
      "OFTEN",
      "REEF",
      "REFER",
      "ROOF",
      "TUFT",
      "TURF"
    ],
    "wordCount": 24,
    "maxScore": 81,
    "theme": "Wealth & luck"
  },
  {
    "id": 40,
    "centerLetter": "G",
    "outerLetters": [
      "A",
      "C",
      "E",
      "I",
      "L",
      "R"
    ],
    "allLetters": [
      "G",
      "A",
      "C",
      "E",
      "I",
      "L",
      "R"
    ],
    "pangrams": [
      "GLACIER"
    ],
    "validWords": [
      "AGILE",
      "AGREE",
      "ALGAE",
      "ALGAL",
      "CAGE",
      "CAGER",
      "CIGAR",
      "CRAG",
      "EAGER",
      "EAGLE",
      "EGGER",
      "GAGE",
      "GALA",
      "GALE",
      "GALL",
      "GEAR",
      "GILL",
      "GIRL",
      "GLACIER",
      "GLARE",
      "GLEE",
      "GRACE",
      "GRAIL",
      "GRILL",
      "LAGER",
      "LARGE",
      "LEGAL",
      "LIEGE",
      "RAGE",
      "REGAL"
    ],
    "wordCount": 30,
    "maxScore": 115,
    "theme": "Frozen ice sheet"
  },
  {
    "id": 41,
    "centerLetter": "S",
    "outerLetters": [
      "A",
      "D",
      "I",
      "L",
      "N",
      "E"
    ],
    "allLetters": [
      "S",
      "A",
      "D",
      "I",
      "L",
      "N",
      "E"
    ],
    "pangrams": [
      "ISLAND"
    ],
    "validWords": [
      "AIDES",
      "AIDS",
      "AISLE",
      "ALIAS",
      "ANISE",
      "ANNAS",
      "ASANA",
      "ASIDE",
      "ASSAI",
      "ASSED",
      "ASSES",
      "DAIS",
      "DALES",
      "DEADS",
      "DEALS",
      "DEANS",
      "DEEDS",
      "DELIS",
      "DELLS",
      "DENSE",
      "DIALS",
      "DIES",
      "DILLS",
      "DINES",
      "EASE",
      "EASED",
      "EASEL",
      "EASES",
      "ELANS",
      "ENDS",
      "ESSES",
      "IDEAS",
      "IDLES",
      "INNS",
      "ISLAND",
      "ISLE",
      "ISLES",
      "LADES",
      "LADS",
      "LANDS",
      "LANES",
      "LASED",
      "LASES",
      "LASS",
      "LEADS",
      "LEANS",
      "LEASE",
      "LENDS",
      "LENS",
      "LESS",
      "LIDS",
      "LIENS",
      "LIES",
      "LINES",
      "LISLE",
      "NAILS",
      "NASAL",
      "NEEDS",
      "NINES",
      "NISEI",
      "SAID",
      "SAIL",
      "SAILS",
      "SALAD",
      "SALE",
      "SALES",
      "SALSA",
      "SAND",
      "SANDS",
      "SANE",
      "SEAL",
      "SEALS",
      "SEAS",
      "SEDAN",
      "SEED",
      "SEEDS",
      "SEEN",
      "SEES",
      "SEINE",
      "SELL",
      "SELLS",
      "SEND",
      "SENDS",
      "SENSE",
      "SIDE",
      "SIDED",
      "SIDES",
      "SIDLE",
      "SILL",
      "SILLS",
      "SINE",
      "SINES",
      "SINS",
      "SISAL",
      "SLAIN",
      "SLED",
      "SLEDS",
      "SLID",
      "SLIDE",
      "SNAIL",
      "SNIDE"
    ],
    "wordCount": 101,
    "maxScore": 389,
    "theme": "Isolated shore"
  },
  {
    "id": 42,
    "centerLetter": "M",
    "outerLetters": [
      "A",
      "C",
      "E",
      "I",
      "L",
      "R"
    ],
    "allLetters": [
      "M",
      "A",
      "C",
      "E",
      "I",
      "L",
      "R"
    ],
    "pangrams": [
      "MIRACLE"
    ],
    "validWords": [
      "AIMER",
      "ALARM",
      "CALM",
      "CAME",
      "CAMEL",
      "CLAIM",
      "CLIME",
      "CRAM",
      "CREAM",
      "CREME",
      "CRIME",
      "EMAIL",
      "EMCEE",
      "LAME",
      "LAMER",
      "LEMMA",
      "LEMME",
      "LIME",
      "LLAMA",
      "MACE",
      "MACER",
      "MAIL",
      "MALE",
      "MALL",
      "MAMMA",
      "MARE",
      "MARIA",
      "MEAL",
      "MECCA",
      "MELEE",
      "MERE",
      "MICE",
      "MILE",
      "MILER",
      "MILL",
      "MIME",
      "MIMER",
      "MIMIC",
      "MIRACLE",
      "REALM",
      "REARM",
      "RIMER"
    ],
    "wordCount": 42,
    "maxScore": 155,
    "theme": "Wondrous marvel"
  },
  {
    "id": 43,
    "centerLetter": "O",
    "outerLetters": [
      "C",
      "P",
      "S",
      "T",
      "U",
      "E"
    ],
    "allLetters": [
      "O",
      "C",
      "P",
      "S",
      "T",
      "U",
      "E"
    ],
    "pangrams": [
      "OCTOPUS"
    ],
    "validWords": [
      "COCO",
      "COCOS",
      "COOP",
      "COOPS",
      "COOTS",
      "COPE",
      "COPES",
      "COPS",
      "COPSE",
      "COSET",
      "COST",
      "COSTS",
      "COTE",
      "COTES",
      "COUP",
      "COUPE",
      "COUPS",
      "ESTOP",
      "OCTET",
      "OCTOPUS",
      "OPTS",
      "OUST",
      "OUSTS",
      "OUTS",
      "PESOS",
      "PESTO",
      "POET",
      "POETS",
      "POOP",
      "POOPS",
      "POPE",
      "POPES",
      "POPS",
      "POSE",
      "POSES",
      "POSET",
      "POSSE",
      "POST",
      "POSTE",
      "POSTS",
      "POUT",
      "POUTS",
      "SCOOP",
      "SCOOT",
      "SCOPE",
      "SCOPS",
      "SCOUT",
      "SECCO",
      "SOOT",
      "SOOTS",
      "SOUP",
      "SOUPS",
      "SOUSE",
      "SPOT",
      "SPOTS",
      "SPOUT",
      "STOOP",
      "STOP",
      "STOPS",
      "STOUP",
      "STOUT",
      "TOES",
      "TOOT",
      "TOOTS",
      "TOPES",
      "TOPOS",
      "TOPS",
      "TOSS",
      "TOTES",
      "TOUT",
      "TOUTS"
    ],
    "wordCount": 71,
    "maxScore": 260,
    "theme": "Eight tentacles"
  },
  {
    "id": 44,
    "centerLetter": "P",
    "outerLetters": [
      "E",
      "H",
      "I",
      "N",
      "O",
      "X"
    ],
    "allLetters": [
      "P",
      "E",
      "H",
      "I",
      "N",
      "O",
      "X"
    ],
    "pangrams": [
      "PHOENIX"
    ],
    "validWords": [
      "EXPO",
      "HIPPO",
      "HOOP",
      "HOPE",
      "OPEN",
      "OPINE",
      "PEEP",
      "PHOENIX",
      "PHONE",
      "PINE",
      "PIPE",
      "PIXIE",
      "POOP",
      "POPE"
    ],
    "wordCount": 14,
    "maxScore": 50,
    "theme": "Reborn from ashes"
  },
  {
    "id": 45,
    "centerLetter": "S",
    "outerLetters": [
      "A",
      "I",
      "L",
      "O",
      "R",
      "E"
    ],
    "allLetters": [
      "S",
      "A",
      "I",
      "L",
      "O",
      "R",
      "E"
    ],
    "pangrams": [
      "SAILOR"
    ],
    "validWords": [
      "AIRS",
      "AISLE",
      "ALIAS",
      "ALOES",
      "ALSO",
      "AREAS",
      "ARIAS",
      "ARISE",
      "AROSE",
      "ARRAS",
      "ARSES",
      "ASSAI",
      "ASSES",
      "EARLS",
      "EARS",
      "EASE",
      "EASEL",
      "EASES",
      "ERAS",
      "ERASE",
      "ERRS",
      "ESSES",
      "IRIS",
      "ISLE",
      "ISLES",
      "LAIRS",
      "LASER",
      "LASES",
      "LASS",
      "LASSO",
      "LEASE",
      "LEERS",
      "LESS",
      "LIARS",
      "LIERS",
      "LIES",
      "LIRAS",
      "LISLE",
      "LOESS",
      "LOLLS",
      "LOOSE",
      "LORES",
      "LOSE",
      "LOSER",
      "LOSES",
      "LOSS",
      "OARS",
      "OASES",
      "OASIS",
      "OILS",
      "OLEOS",
      "OLIOS",
      "ORALS",
      "ORES",
      "OSIER",
      "RAILS",
      "RAISE",
      "RASAE",
      "REALS",
      "REARS",
      "REELS",
      "RIALS",
      "RILES",
      "RILLS",
      "RISE",
      "RISER",
      "RISES",
      "ROARS",
      "ROILS",
      "ROLES",
      "ROLLS",
      "ROSE",
      "ROSES",
      "SAIL",
      "SAILOR",
      "SAILS",
      "SALE",
      "SALES",
      "SALSA",
      "SARIS",
      "SEAL",
      "SEALS",
      "SEAR",
      "SEARS",
      "SEAS",
      "SEERS",
      "SEES",
      "SELL",
      "SELLS",
      "SILL",
      "SILLS",
      "SILO",
      "SILOS",
      "SIRE",
      "SIREE",
      "SIRES",
      "SISAL",
      "SLIER",
      "SLOES",
      "SOAR",
      "SOARS",
      "SOIL",
      "SOILS",
      "SOLAR",
      "SOLE",
      "SOLES",
      "SOLO",
      "SOLOS",
      "SORE",
      "SORER",
      "SORES"
    ],
    "wordCount": 111,
    "maxScore": 431,
    "theme": "Seafaring voyager"
  },
  {
    "id": 46,
    "centerLetter": "L",
    "outerLetters": [
      "C",
      "E",
      "O",
      "P",
      "S",
      "A"
    ],
    "allLetters": [
      "L",
      "C",
      "E",
      "O",
      "P",
      "S",
      "A"
    ],
    "pangrams": [
      "TELESCOPE"
    ],
    "validWords": [
      "ALOE",
      "ALOES",
      "ALSO",
      "APPLE",
      "CALL",
      "CALLA",
      "CALLS",
      "CELL",
      "CELLO",
      "CELLS",
      "CLAP",
      "CLAPS",
      "CLASP",
      "CLASS",
      "CLOPS",
      "CLOSE",
      "COAL",
      "COALS",
      "COLAS",
      "COOL",
      "COOLS",
      "EASEL",
      "ELOPE",
      "LACE",
      "LACES",
      "LAPEL",
      "LAPS",
      "LAPSE",
      "LASES",
      "LASS",
      "LASSO",
      "LEAP",
      "LEAPS",
      "LEASE",
      "LESS",
      "LOCAL",
      "LOCOS",
      "LOESS",
      "LOLLS",
      "LOOP",
      "LOOPS",
      "LOOSE",
      "LOPES",
      "LOSE",
      "LOSES",
      "LOSS",
      "OLEOS",
      "OPAL",
      "OPALS",
      "PALE",
      "PALES",
      "PALLS",
      "PAPAL",
      "PEAL",
      "PEALS",
      "PEEL",
      "PEELS",
      "PLACE",
      "PLEA",
      "PLEAS",
      "PLOPS",
      "POLE",
      "POLES",
      "POLL",
      "POLLS",
      "POLO",
      "POLOS",
      "POOL",
      "POOLS",
      "SALE",
      "SALES",
      "SALSA",
      "SCALE",
      "SCALP",
      "SEAL",
      "SEALS",
      "SELL",
      "SELLS",
      "SEPAL",
      "SLAP",
      "SLAPS",
      "SLEEP",
      "SLOES",
      "SLOOP",
      "SLOPE",
      "SLOPS",
      "SOCLE",
      "SOLE",
      "SOLES",
      "SOLO",
      "SOLOS",
      "SPELL",
      "SPOOL",
      "TELESCOPE"
    ],
    "wordCount": 94,
    "maxScore": 361,
    "theme": "Stargazer optic"
  },
  {
    "id": 47,
    "centerLetter": "V",
    "outerLetters": [
      "A",
      "I",
      "L",
      "N",
      "T",
      "E"
    ],
    "allLetters": [
      "V",
      "A",
      "I",
      "L",
      "N",
      "T",
      "E"
    ],
    "pangrams": [
      "VALIANT"
    ],
    "validWords": [
      "ALIVE",
      "ANVIL",
      "AVAIL",
      "AVANT",
      "AVIAN",
      "EVEN",
      "EVENT",
      "EVIL",
      "LAVA",
      "LEAVE",
      "LEVEE",
      "LEVEL",
      "LIVE",
      "LIVEN",
      "NAIVE",
      "NAVAL",
      "NAVEL",
      "VALE",
      "VALET",
      "VALIANT",
      "VALVE",
      "VANE",
      "VEAL",
      "VEIL",
      "VEIN",
      "VENAL",
      "VENT",
      "VIAL",
      "VILLA",
      "VILLE",
      "VILLI",
      "VINE",
      "VITAE",
      "VITAL"
    ],
    "wordCount": 34,
    "maxScore": 131,
    "theme": "Heroic valor"
  },
  {
    "id": 48,
    "centerLetter": "Z",
    "outerLetters": [
      "B",
      "I",
      "L",
      "R",
      "A",
      "D"
    ],
    "allLetters": [
      "Z",
      "B",
      "I",
      "L",
      "R",
      "A",
      "D"
    ],
    "pangrams": [
      "BLIZZARD"
    ],
    "validWords": [
      "BAZAR",
      "BLIZZARD"
    ],
    "wordCount": 2,
    "maxScore": 50,
    "theme": "Fierce winter storm"
  },
  {
    "id": 49,
    "centerLetter": "K",
    "outerLetters": [
      "A",
      "C",
      "N",
      "O",
      "R",
      "T"
    ],
    "allLetters": [
      "K",
      "A",
      "C",
      "N",
      "O",
      "R",
      "T"
    ],
    "pangrams": [
      "TRACKON"
    ],
    "validWords": [
      "COCK",
      "CONK",
      "COOK",
      "CORK",
      "CRACK",
      "CRANK",
      "CROAK",
      "CROCK",
      "CROOK",
      "KARAT",
      "KNACK",
      "KNOCK",
      "KNOT",
      "KRONA",
      "NOOK",
      "OKRA",
      "RACK",
      "RANK",
      "ROCK",
      "ROOK",
      "TACK",
      "TANK",
      "TOOK",
      "TRACK",
      "TRACKON"
    ],
    "wordCount": 25,
    "maxScore": 78,
    "theme": "Pathways & trails"
  },
  {
    "id": 50,
    "centerLetter": "M",
    "outerLetters": [
      "A",
      "C",
      "E",
      "H",
      "I",
      "N"
    ],
    "allLetters": [
      "M",
      "A",
      "C",
      "E",
      "H",
      "I",
      "N"
    ],
    "pangrams": [
      "MACHINE"
    ],
    "validWords": [
      "AMEN",
      "AMINE",
      "ANIMA",
      "CAME",
      "CHIME",
      "EMCEE",
      "ENEMA",
      "MACE",
      "MACHINE",
      "MAIN",
      "MAMMA",
      "MANE",
      "MANIA",
      "MANIC",
      "MANNA",
      "MEAN",
      "MECCA",
      "MICE",
      "MIME",
      "MIMIC",
      "MINCE",
      "MINE",
      "MINIM",
      "NAME"
    ],
    "wordCount": 24,
    "maxScore": 89,
    "theme": "Mechanical engine"
  }
];
